using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using UnityEngine.TestTools;
using MizoreNekoyanagi.PublishUtil.PackageExporter.FileList;
using Object = UnityEngine.Object;

namespace MizoreNekoyanagi.PublishUtil.PackageExporter.Tests
{
    /// <summary>
    /// Project ウィンドウで exporter asset を作成し、対象 asset を登録し、
    /// FileList で確認してから Export を押す通常フロー寄りの回帰テスト。
    /// </summary>
    public class PackageExporterUserFlowTests
    {
        const string TEST_ROOT = "Assets/Tests_MizorePkgExp_UserFlow";
        const string EXPORTER_FOLDER = TEST_ROOT + "/Exporters";
        const string CONTENT_FOLDER = TEST_ROOT + "/PackageContent";
        const string MATERIAL_PATH = CONTENT_FOLDER + "/UserMaterial.mat";
        const string README_PATH = CONTENT_FOLDER + "/readme.txt";
        const string MISSING_PATH = CONTENT_FOLDER + "/DeletedBeforeExport.mat";
        const string OUTPUT_FOLDER = "MizorePackageExporter";

        PathType _originalDefaultPathType;
        bool _originalLockEditor;

        [SetUp]
        public void SetUp()
        {
            _originalDefaultPathType = ExporterEditorPrefs.DefaultPathType;
            _originalLockEditor = MizoresPackageExporter.LockEditor;
            MizoresPackageExporter.LockEditor = false;

            CleanupGeneratedAssets();
            CleanupOutputPackage("UserFlowExporter");
            CleanupOutputPackage("MissingFileExporter");

            Directory.CreateDirectory(EXPORTER_FOLDER);
            Directory.CreateDirectory(CONTENT_FOLDER);
            File.WriteAllText(README_PATH, "readme generated by user flow test");
            AssetDatabase.Refresh();

            CreateTestMaterialAsset(MATERIAL_PATH);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        [TearDown]
        public void TearDown()
        {
            ExporterEditorPrefs.DefaultPathType = _originalDefaultPathType;
            MizoresPackageExporter.LockEditor = _originalLockEditor;

            CleanupGeneratedAssets();
            CleanupOutputPackage("UserFlowExporter");
            CleanupOutputPackage("MissingFileExporter");
            AssetDatabase.Refresh();
        }

        [UnityTest]
        public IEnumerator UserCreatesExporter_AddsFolderInProjectWindow_PreviewsAndExportsPackage()
        {
            ExporterEditorPrefs.DefaultPathType = PathType.Relative;
            var exporter = CreateExporterAsset("UserFlowExporter");
            exporter.packageNameSettings.packageName = "%name%";

            var folderObject = AssetDatabase.LoadAssetAtPath<DefaultAsset>(CONTENT_FOLDER);
            Assert.IsNotNull(folderObject, "前提: Project ウィンドウで選択できるフォルダ asset が存在すること");

            ExporterUtils.AddObjects(new[] { exporter }, item => item.objects, new Object[] { folderObject });
            Assert.AreEqual(1, exporter.objects.Count, "ドラッグ追加と同じ経路で objects に1件追加されること");
            Assert.IsTrue(PathUtils.IsRelativePath(exporter.objects[0].Path),
                "DefaultPathType.Relative の通常設定では exporter からの相対パスとして保存されること");
            Assert.AreEqual(CONTENT_FOLDER, exporter.objects[0].GetConvertedPath(exporter),
                "保存された相対パスは元のフォルダ asset path に戻ること");

            CreateFileList.FileListData preview = null;
            yield return WaitForTask(CreateFileList.Create(new[] { exporter }, null, data => preview = data));
            Assert.IsNotNull(preview, "FileList 作成完了時に preview データが返ること");
            Assert.AreEqual(1, preview.packages.Count, "Single export では FileList に1つの package が表示されること");
            var exportPath = exporter.GetExportPath(string.Empty);
            CollectionAssert.Contains(preview.packages, exportPath,
                "FileList の package 一覧に exporter の出力先が含まれること");

            var logs = new ExporterEditorLogs();
            yield return WaitForTask(FileListWindow.Export(logs, new[] { exporter }, new HashSet<string>(preview.packages)));

            Assert.IsTrue(File.Exists(exportPath), "FileList で選択した unitypackage が作成されること");
            Assert.Greater(new FileInfo(exportPath).Length, 0, "作成された unitypackage が空ファイルではないこと");
            Assert.IsTrue(logs.logs.Any(log => log.type == ExporterEditorLogs.LogType.Info && log.text == ExporterTexts.ExportLogSuccess(exportPath)),
                "エクスポート成功ログが出ること");
            Assert.IsFalse(MizoresPackageExporter.LockEditor, "エクスポート完了後は編集ロックが解除されること");
        }

        [UnityTest]
        public IEnumerator UserExportsStalePath_NotFoundIsLoggedAndPackageIsNotCreated()
        {
            var exporter = CreateExporterAsset("MissingFileExporter");
            exporter.packageNameSettings.packageName = "%name%";
            exporter.objects.Add(new ExportTargetObjectElement(MISSING_PATH) { searchReference = false });

            var exportPath = exporter.GetExportPath(string.Empty);
            var logs = new ExporterEditorLogs();
            LogAssert.Expect(LogType.Error, ExporterTexts.ExportLogNotFound(MISSING_PATH));
            LogAssert.Expect(LogType.Error, ExporterTexts.ExportLogFailed(exportPath));
            yield return WaitForTask(FileListWindow.Export(logs, new[] { exporter }, new HashSet<string> { exportPath }));

            Assert.IsFalse(File.Exists(exportPath), "存在しない対象を含む場合は unitypackage を作成しないこと");
            Assert.IsTrue(logs.logs.Any(log => log.type == ExporterEditorLogs.LogType.Error && log.text == ExporterTexts.ExportLogNotFound(MISSING_PATH)),
                "存在しない対象パスが Error ログに出ること");
            Assert.IsTrue(logs.logs.Any(log => log.type == ExporterEditorLogs.LogType.Error && log.text == ExporterTexts.ExportLogFailed(exportPath)),
                "エクスポート失敗ログが出ること");
            Assert.IsFalse(MizoresPackageExporter.LockEditor, "失敗後も編集ロックが解除されること");
        }

        [Test]
        public void UserDefaultPathTypeRelative_DraggedObjectIsStoredAsRelativePathAndResolvedBack()
        {
            var exporter = CreateExporterAsset("RelativePathExporter");
            var material = AssetDatabase.LoadAssetAtPath<Material>(MATERIAL_PATH);
            Assert.IsNotNull(material, "前提: 登録対象の Material が存在すること");

            ExporterEditorPrefs.DefaultPathType = PathType.Relative;
            var element = new ObjectRefElement();
            element.SetPathAutoDetect(exporter, material);

            Assert.IsFalse(element.IsGUID);
            Assert.IsTrue(PathUtils.IsRelativePath(element.Path), "Relative 設定では相対パスとして保存されること");
            Assert.AreEqual(MATERIAL_PATH, element.GetConvertedPath(exporter), "相対パスから元の asset path に戻ること");
            Assert.AreEqual(material, element.GetObject(exporter), "相対パス保存でも元の Object を取得できること");
        }

        [Test]
        public void UserDefaultPathTypeGuid_DraggedObjectIsStoredAsGuidAndResolvedBack()
        {
            var exporter = CreateExporterAsset("GuidPathExporter");
            var material = AssetDatabase.LoadAssetAtPath<Material>(MATERIAL_PATH);
            Assert.IsNotNull(material, "前提: 登録対象の Material が存在すること");

            ExporterEditorPrefs.DefaultPathType = PathType.GUID;
            var element = new ObjectRefElement();
            element.SetPathAutoDetect(exporter, material);

            var expectedGuid = AssetDatabase.AssetPathToGUID(MATERIAL_PATH);
            Assert.IsTrue(element.IsGUID);
            Assert.AreEqual(expectedGuid, element.Path, "GUID 設定では asset GUID として保存されること");
            Assert.AreEqual(MATERIAL_PATH, element.GetConvertedPath(exporter), "GUID から元の asset path に戻ること");
            Assert.AreEqual(material, element.GetObject(exporter), "GUID 保存でも元の Object を取得できること");
        }

        [Test]
        public void UserDefaultPathTypeAbsolute_DraggedObjectIsStoredAsAssetPathAndResolvedBack()
        {
            var exporter = CreateExporterAsset("AbsolutePathExporter");
            var material = AssetDatabase.LoadAssetAtPath<Material>(MATERIAL_PATH);
            Assert.IsNotNull(material, "前提: 登録対象の Material が存在すること");

            ExporterEditorPrefs.DefaultPathType = PathType.Absolute;
            var element = new ObjectRefElement();
            element.SetPathAutoDetect(exporter, material);

            Assert.IsFalse(element.IsGUID);
            Assert.AreEqual(MATERIAL_PATH, element.Path, "Absolute 設定では Unity の asset path として保存されること");
            Assert.AreEqual(MATERIAL_PATH, element.GetConvertedPath(exporter), "asset path はそのまま解決されること");
            Assert.AreEqual(material, element.GetObject(exporter), "asset path 保存でも元の Object を取得できること");
        }

        static IEnumerator WaitForTask(Task task)
        {
            while (!task.IsCompleted)
            {
                yield return null;
            }

            if (task.IsFaulted)
            {
                throw task.Exception.InnerException ?? task.Exception;
            }

            if (task.IsCanceled)
            {
                Assert.Fail("Task がキャンセルされました");
            }
        }

        static MizoresPackageExporter CreateExporterAsset(string exporterName)
        {
            var exporter = ScriptableObject.CreateInstance<MizoresPackageExporter>();
            exporter.name = exporterName;
            var path = EXPORTER_FOLDER + "/" + exporterName + ".asset";
            AssetDatabase.CreateAsset(exporter, path);
            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
            return AssetDatabase.LoadAssetAtPath<MizoresPackageExporter>(path);
        }

        static void CreateTestMaterialAsset(string assetPath)
        {
            var template = AssetDatabase.GetBuiltinExtraResource<Material>("Default-Material.mat");
            Material material;
            if (template != null)
            {
                material = new Material(template);
            }
            else
            {
                var shader = Shader.Find("Standard")
                    ?? Shader.Find("Sprites/Default")
                    ?? Shader.Find("Legacy Shaders/Diffuse");
                if (shader == null)
                {
                    throw new System.InvalidOperationException("テスト用 Material を生成するための Shader が見つかりません。");
                }

                material = new Material(shader);
            }

            material.name = Path.GetFileNameWithoutExtension(assetPath);
            AssetDatabase.CreateAsset(material, assetPath);
        }

        static void CleanupGeneratedAssets()
        {
            if (AssetDatabase.IsValidFolder(TEST_ROOT))
            {
                AssetDatabase.DeleteAsset(TEST_ROOT);
            }
            else if (Directory.Exists(TEST_ROOT))
            {
                Directory.Delete(TEST_ROOT, recursive: true);
            }
        }

        static void CleanupOutputPackage(string exporterName)
        {
            var packagePath = Path.Combine(OUTPUT_FOLDER, exporterName + ".unitypackage");
            if (File.Exists(packagePath))
            {
                File.Delete(packagePath);
            }

            if (Directory.Exists(OUTPUT_FOLDER) && !Directory.EnumerateFileSystemEntries(OUTPUT_FOLDER).Any())
            {
                Directory.Delete(OUTPUT_FOLDER);
            }
        }
    }
}
